### ISSUE TITLE
Problems getting the Satterthwaite or Kenward-Roger p values

### ISSUE THREAD

**Issue by Benambridge** [palday/JellyMe4.jl#54] opened 2021-09-13 13:27 UTC
Hi

I'm probably doing something really obvious wrong here, but I'm trying and failing to get lmerTest style p values calculated via Satterthwaite or Kenward-Roger ddf, but all I get is the lme4 style ones (approximated via the z distribution). Can anyone see what I'm doing wrong?
```R
library(JuliaCall)
j=julia_setup() # Setup Julia
j$assign("Data", contextdata) # Copy the data from R into Julia

# Maximal model for Predictions 1 and 2
j$assign("Maximal1", Response ~ SentenceType/ContextType + (1+SentenceType/ContextType|Verb) + (1+SentenceType/ContextType|Participant)) #Get the formula into Julia
j$assign("Maximal2", Response ~ SentenceType*ContextType + (1+SentenceType*ContextType|Verb) + (1+SentenceType*ContextType|Participant)) #Get the formula into Julia

julia_console()
ENV["LMER"] = "lmerTest::lmer" # if you really need Satterthwaite or Kenward-Roger ddf
using MixedModels, RCall, JellyMe4 # Need to use JellyMe4 to use the lmerTest backend for the better p values
Julia_Model1 = fit(LinearMixedModel, Maximal1, Data) ###Hmm it still reports it as z and Pr(>|z|) - is it really using Satterthwaite or Kenward-Roger?
Julia_Model2 = fit(LinearMixedModel, Maximal2, Data) ###Hmm it still reports it as z and Pr(>|z|) - is it really using Satterthwaite or Kenward-Roger?
```

Thanks
Ben

**Comment by palday** [comment] 2021-09-13 14:18
Only the fit itself is transferred; none of the derived quantities are. More specifically: the t- and p-values are computed in whatever language you're currently in. So setting the `LMER` environmental variable only impacts which `lmer` definition is used in R.

Putting on my hat as one of the the MixedModels.jl developers:
MixedModels.jl does not support the Satterthwaite or Kenward-Roger approximations and probably never will.
1. For large models, you can effectively treat the degrees of freedom as being "infinite" because the t-distribution rather rapidly converges to the z distribution when the df are above 30 or so. In other words, using some approximation to find that with 20+ participants and 20+ items, you have df on the order of several hundred isn't worthwhile because you're so close to the z distribution that the approximation error is bigger than the error you get from not correcting the df.  (And this is assuming that the correct sampling distribution for the error terms is even t/z, which comes with a lot of fine print. You can avoid that by using the bootstrap, see (5) below.) 
2. Both of these approximations are formulated in computationally messy ways. Kenward-Roger in particular requires computing the inverse of a matrix of dimension nobs x nobs, which is very very slow and memory intensive. Satterthwaite could in principle be done, but this would involve evaluating the gradient, which we intentionally avoid.
3. We do have leverage implemented, which could be used to compute a geometric notion of degrees of freedom. In classical linear regression, the sum of the leverage values can be straightforwardly interpreted as the degrees of freedom; we feel that the generalization to the linear mixed model also works rather well for this as well (see e.g.  [here](https://repsychling.github.io/SMLP2021/notebooks/sleepstudy.html) and [here](https://repsychling.github.io/SMLP2021/notebooks/shrinkageplot.html)). 
4.  BUT: There might not a single correct answer to the degrees of freedom question for very deep reasons, and that's okay. The important thing is again that the degrees of freedom in many designs are so large that it really doesn't matter (see (1) above).
4. P-values are not something we really want to encourage people to use. Instead, use bootstrapped confidence intervals. With `parametricbootstrap` and `shortestcovint` in MixedModels.jl, you can often perform 1000 bootstrap replications as fast as computing the KR df approximation in R.
5. Maximal models probably aren't the way to go, see e.g. [here](https://doi.org/10.1016/j.jml.2017.01.001), [here](https://arxiv.org/abs/1506.04967) and [here](https://doi.org/10.33016/nextjournal.100002).

**Comment by Benambridge** [comment] 2021-09-13 17:00
Thanks very much! I'll just use the p values from the Z distribution then (the df will be well above 30). (I can completely see why they are discouraged in some circles, but I've personally been quite persuaded by the error-control arguments in favour of p values advanced by people like Deborah Mayo and Daniel Lakens -not to bring up that whole debate here!). And thanks especially for the links about maximal models - I'll use the model-comparison method you linked to to simplify the random effects structure

Thanks
Ben

**Closed** 2021-09-14 13:42 UTC
